apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
commonLabels:
  env: dev
nameSuffix: -circle-Id
images:
  - name: quiz-app
    newName: thallesf/quiz-app
    newTag: dev
resources:
  - ../../base

patchesStrategicMerge:
  - deployment.yaml