apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
commonLabels:
  env: dev
nameSuffix: circle-id
images:
  - name: quiz-app
    newName: thallesf/quiz-app
    newTag: 1.0
resources:
  - ../../base

patchesStrategicMerge:
  - deployment.yaml
