apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-app-backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-app-backend
      version: quiz-app-backend
      component: quiz-app-backend
      tag: "1.0"
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: '{{ .Values.istio.enabled }}'
      labels:
        app: quiz-app-backend
        version: quiz-app-backend
        component: quiz-app-backend
        tag: "1.0"
    spec:
      serviceAccountName: default
      containers:
        - name: quiz-app-backend
          image: "quiz-app"