apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - deployment.yaml
    - service.yaml
commonLabels:
  app: quiz-app-backend
  version: quiz-app-backend
  component: quiz-app-backend
  tag: "1.0"

