apiVersion: v1
kind: Service
metadata:
  name: quiz-app-backend

spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: quiz-app-backend
    version: quiz-app-backend
    component: quiz-app-backend
    tag: "1.0"
